version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Build
          command: swift build
      - run:
          name: Test
          command: swift test
      - run:
          name: Build Specs
          command: ./build_generated_specs.sh
